### ISSUE TITLE
cooking watch占内存

### ISSUE THREAD

**Issue by HuanMeng0** [ElemeFE/cooking#101]
使用的是最新版本的cooking 

watch命令的内存占用会达到300MB以上
![image](https://cloud.githubusercontent.com/assets/11138015/19407556/62124a2a-92d8-11e6-9bed-74525a5ea375.png)

**Comment by QingWei-Li** [comment]
正常应该是多少？

**Comment by HuanMeng0** [comment]
100MB一下，或150MB左右

**Comment by QingWei-Li** [comment]
你用 vue cli 在同样的环境下创建个项目启动一下以及用 cooking 创建的项目启动下截图我看看

mac 下没这问题

**Comment by HuanMeng0** [comment]
看来是我项目使用的库有点多
![image](https://cloud.githubusercontent.com/assets/11138015/19409235/56d5c662-9302-11e6-84be-e99a1d8d3538.png)

请问我该如何优化watch命令占用的内存？
