### ISSUE TITLE
后续版本会用yarn来管理包吗?

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/cooking#102]
后续版本会用yarn来管理包吗? yarn安装速度比npm快太多了...

啥时候webpack2的版本能更新到 > beta.22

**Comment by QingWei-Li** [comment]
1. 好主意
2. 等 webpack 稳定了吧，一版本变一下我小心脏受不鸟，25 变动太大了不支持 webpack 选项以外的自定义选项，都不知道一堆插件或者 loader 要怎么传配置了

**Comment by lincenying** [comment]
https://github.com/webpack/webpack.js.org/blob/develop/content/how-to/upgrade-from-webpack-1.md

**Comment by QingWei-Li** [comment]
1.2.0 已发布，支持 yarn 和新版 webpack 配置项，老的配置同样兼容
