### ISSUE TITLE
关于vue-router2中懒加载问题

### ISSUE THREAD

**Issue by minerchow** [ElemeFE/cooking#104]
![image](https://cloud.githubusercontent.com/assets/3675138/19894300/768e293a-a087-11e6-9469-6f4d9edfa812.png)
![image](https://cloud.githubusercontent.com/assets/3675138/19894332/97b0a39a-a087-11e6-9548-a2163fc266a4.png)
cooking配置是基于多页面vue2这个demo改的，现在npm run dist没法将js文件切割0.js,1.js,2.js.....

**Comment by lincenying** [comment]
https://github.com/webpack/webpack.js.org/blob/develop/content/how-to/upgrade-from-webpack-1.md#code-splitting-with-es6

**Comment by minerchow** [comment]
![image](https://cloud.githubusercontent.com/assets/3675138/19968802/04c5cc8c-a211-11e6-9685-862a3155044f.png)
换成vue-router官方例子也不行

**Comment by lincenying** [comment]
你webpack什么版本的?

**Comment by minerchow** [comment]
用cooking跑的项目，webpack版本是1.12

**Comment by QingWei-Li** [comment]
vue 问题请到 vue 论坛或相关社区咨询
