### ISSUE TITLE
更新了cooking-cli后build报错.

### ISSUE THREAD

**Issue by djjandyhl** [ElemeFE/cooking#109]
### cooking version
1.2.0 

cooking build 报错...

Vue packages version mismatch:

- vue@2.0.3
- vue-template-compiler@2.0.1

不知道去哪修改vue-template-compiler的版本号....
这是我的package.json
{
  "name": "element-cooking-starter",
  "version": "0.0.0",
  "description": "",
  "private": false,
  "keywords": [],
  "scripts": {
    "dev": "cooking watch -p",
    "dist": "cooking build -p",
    "deploy": "cooking build --no-color"
  },
  "author": "",
  "license": "MIT",
  "dependencies": {
    "babel-polyfill": "*",
    "element-ui": "^1.0.1",
    "vue": "2.0.3",
    "vue-resource": "^1.0.3",
    "vue-router": "^2.0.0"
  },
  "devDependencies": {
    "cooking-vue2": "*"
  }
}

**Comment by QingWei-Li** [comment]
这和 cooking 无关，vue-template-compiler 和 vue 的版本要同步，可以自己安装锁死两者的版本，然后手动同步

**Comment by djjandyhl** [comment]
我现在只能把我的vue的版本号改为2.0.1才能正常使用了。
不知道怎么来处理这个问题....能不能说的详细一点呢....

**Comment by QingWei-Li** [comment]
Vue 分两个版本，一个是包含了 runtime 和 compiler，另一个是 runtime，complier 独立一个包 https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler

两者版本要同步，vue-loader 依赖 vue-template-complier, 这样在安装时可能会出现 vue 和 compiler 版本不同步的问题，最后自己在 package.json 锁死两者的版本

```json
{
  "vue": "2.0.6",
  "vue-template-compiler": "2.0.6"
}
```

**Comment by djjandyhl** [comment]
我按照你说的把这2个相同的版本配置到我的package.json中。然后npm install。然后cooking build还是一样的报错。
我想的是之前我的配置中都没有申明vue-loader这些依赖，好像这些都是在cooking当中做的配置。
然后我也不知道怎么做了......求指导....
