### ISSUE TITLE
在用vue-router. 懒加载出问题. 还有新版cooking问题

### ISSUE THREAD

**Issue by Super-Meng** [ElemeFE/cooking#124]
还有更新新版cooking后.webpack不断提示超过250kb.是在头疼.
在此求大神打救....

**Comment by QingWei-Li** [comment]
cooking 刚才发布的 1.2.8 似乎已经解决了 webpack 提示的问题

vue-router 的问题请到 vue-router 仓库下咨询

**Comment by CCWork** [comment]
我已更新到1.2.8 但依旧存在 webpack不断提示超过250kb

**Comment by QingWei-Li** [comment]
是 babel 的提示么 请截个图或贴报错的信息

**Comment by CCWork** [comment]
![image](https://cloud.githubusercontent.com/assets/7381733/21180798/9303645c-c235-11e6-890b-d1904bf4513a.png)

**Comment by QingWei-Li** [comment]
这个确实是修复了 检查下版本是不是 1.2.8 以及内部的 2webpack2 这个包的版本是不是 0.5.1

**Comment by CCWork** [comment]
好的 谢谢

**Comment by CCWork** [comment]
我重新更新了一下cooking就好了 应该是我之前更新有误 抱歉。

**Comment by Super-Meng** [comment]
非常感谢. 更新cooking^1.2.8已修复问题.

**Comment by Super-Meng** [comment]
大神继续求助...
