### ISSUE TITLE
Cooking配置执行时说软件版本不统一该怎么改啊

### ISSUE THREAD

**Issue by feifanyajun** [ElemeFE/cooking#128]
### What is actually happening?
![image](https://cloud.githubusercontent.com/assets/19487214/21257076/e0599042-c3b0-11e6-8dbf-1d0a27bba245.png)

**Comment by lincenying** [comment]
升级vue到2.1.6版本

**Comment by QingWei-Li** [comment]
这是 vue 的问题 
@lincenying 给了解决方案

**Comment by minerchow** [comment]
![image](https://cloud.githubusercontent.com/assets/3675138/21541267/f411bec2-cdef-11e6-92e4-1921ba3624a4.png)

升级到2.1.6还是报错
