### ISSUE TITLE
1.2.9和1.2.10eslint不正常显示

### ISSUE THREAD

**Issue by saopang** [ElemeFE/cooking#129]
windows10
node: 6.2.0
npm: 3.10.8

1.2.8及之前版本正常，
升级到1.2.9之后发现，如果有语法错误（如多了一个空行）会报错

但是，删掉多余空行之后，错误信息不会清空

猜测是这次提交引起的问题：
https://github.com/ElemeFE/cooking/commit/1adf0cb79bc8aa0c65fc81d29e55da0b68f12224#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by lincenying** [comment]
你应该把错误信息贴出来, 而不是这个

**Comment by saopang** [comment]
@lincenying 多一个空行报错：
![image](https://cloud.githubusercontent.com/assets/11707936/21284060/050d0578-c44b-11e6-8560-1ca53de634b7.png)
![image](https://cloud.githubusercontent.com/assets/11707936/21284061/0d25f832-c44b-11e6-8a96-6880aae46fc5.png)
删掉多余的空行后错误信息不会消失

**Comment by QingWei-Li** [comment]
麻烦给一个能复现问题的示例项目

**Comment by QingWei-Li** [comment]
重装下就好了

**Comment by saopang** [comment]
上周重装了n次没成功，从1.2.5到1.2.10，每一个版本试了2次，1.2.9+都是上述问题，本周卸载重装1.2.10，神奇地好了，好神奇！

**Comment by QingWei-Li** [comment]
我也没找到到底哪个依赖升级导致的，本来我的也有问题，升级依赖就好了...

**Comment by saopang** [comment]
@QingWei-Li 不知道是我写的有问题，还是vue-router文档有问题，
https://router.vuejs.org/zh-cn/advanced/lazy-loading.html
按照文档的简写分块异步加载有如下问题：
从同步组件切换到异步组件正常，再切到同步组件，再切换到异步组件，异步组件就不显示了
```js
// 分块，异步加载（切换有问题）
const a = resolve => require(['src/components/wx/a.vue'], resolve);

// 分块，同步加载，切换正常
const a = require('bundle-loader!src/components/wx/a.vue');

// 分块，异步加载，切换正常
const a = resolve => {
  require.ensure(['src/components/wx/a.vue'], () => {
  resolve(require('src/components/wx/a.vue'));
  });
};
```

如果你看到了这里，能否顺便告知异步组件的打包出来的js的路径怎么修改，直接修改publicPath的话，js和img图片和css图片的地址不就麻烦了

**Comment by QingWei-Li** [comment]
@saopang 请给 demo 项目
