### ISSUE TITLE
cooking可否自定义设置devtool？

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/cooking#130]
development模式默认是eval-source-map
想修改sourcemap方式
例如
`cooking.add("devtool","cheap-module-source-map")`

看了下源码 貌似写死了？

**Comment by QingWei-Li** [comment]
我没记错的话 sourceMap 支持字符串的
```js
cooking.set({
  sourceMap: 'cheap-module-source-map'
})
```

**Comment by yelingfeng** [comment]
我设置了但是 为啥编译的app.js 为啥还是eval的
![image](https://cloud.githubusercontent.com/assets/1932350/21343098/1f0e454a-c6d0-11e6-8102-f16d9556a1f7.png)

**Comment by QingWei-Li** [comment]
fixed in `1.2.11`
