### ISSUE TITLE
请问官网演示用的编辑器是什么？

### ISSUE THREAD

**Issue by itfan** [ElemeFE/cooking#133]
https://elemefe.github.io/cooking/

右上角的编辑器和左侧的预览，很方便。谢谢。

请问演示用的编辑器是什么？

**Comment by QingWei-Li** [comment]
Chrome + Sublime + iTerm2 组合而成

**Comment by itfan** [comment]
@QingWei-Li   那是Sublime ？我没看出来。。。难道是自定义了主题？

**Comment by QingWei-Li** [comment]
material theme

**Comment by itfan** [comment]
@QingWei-Li  非常感谢
