### ISSUE TITLE
output.filename 不能设置

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/cooking#134]
期望可以配置output.filename
以下二种都不可以
```
  cooking.set({
    'output.filename': 'js/[name].js'
  })

  cooking.add('output.filename','js/[name].js')
```

**Comment by QingWei-Li** [comment]
第二种是可以的 https://github.com/ElemeFE/element/blob/27affb22c0b5535cb0d31dc1fb4c0c33c5c3044c/build/cooking.common.js#L15

**Comment by yelingfeng** [comment]
知道为啥了 ， 我再set之前 add的 所以一直不好使 ：）
