### ISSUE TITLE
1.3.1版本警告 Using NoErrorsPlugin is deprecated. Use NoEmitOnErrorsPlugin instead.

### ISSUE THREAD

**Issue by zhangyanzt** [ElemeFE/cooking#139]
### cooking version
1.3.1

### What is actually happening?
升级到1.3.1版本后，出现了
`WARNING in webpack: Using NoErrorsPlugin is deprecated.
Use NoEmitOnErrorsPlugin instead.`
的警告信息，虽说不影响使用，不过看着页面黄色的警告不消失挺闹心的。

**Comment by QingWei-Li** [comment]
嗯 webpack rc4 出现的提示，我兼容下

**Comment by tangshiping** [comment]
还没有修复吗？

**Comment by QingWei-Li** [comment]
忘了，`1.3.2` 已发布
