### ISSUE TITLE
cooking-cli是不是少了依赖啊

### ISSUE THREAD

**Issue by db-murphy** [ElemeFE/cooking#141]
`[09:57:40] No local gulp install found in /Users/apple/.cooking/node_modules/slush-cooking-vue
[slush] This is an issue with the `slush-cooking-vue` generator
`

我看了下node-modules 确实很多模块没安装啊  那个package.json里面也没申明

**Comment by db-murphy** [comment]
最后我自己跑到.cooking/node_modules/slush-cooking-vue 下面去  把那些模块自己装了一遍   为什么slush-cooking-vue 这个模块不把依赖写好呢？

**Comment by QingWei-Li** [comment]
先确定是不是自己的问题再跑来抱怨，为啥其他人用着没问题。

注意看文档：确定用的是不是 NPM3

**Comment by db-murphy** [comment]
$ npm -v

3.10.10

**Comment by QingWei-Li** [comment]
第一次使用时会下载 [`generator-package-cooking`](https://github.com/cookingjs/generator-package-cooking) 这里面包含了脚手架所需要的基本依赖。npm 版本没问题，那么看下你的用户根目录下是不是有 `node_modules`，在 `~/node_modules` 里，有的话就把这个删掉。

**Comment by db-murphy** [comment]
有可能是我的nvm引起的  我排查下  多谢解答
