### ISSUE TITLE
请问cooking中如何使用eslint的命令行

### ISSUE THREAD

**Issue by 1615450788** [ElemeFE/cooking#145]
请问cooking中如何使用eslint的命令行，安装了全局的eslint命令行也不行
![image](https://cloud.githubusercontent.com/assets/15265570/22181515/2f1f65fa-e0c9-11e6-8739-c84bf1c305c4.png)
依赖的babel-eslint还有eslint-plugin-vue都安装了，配置如下
![image](https://cloud.githubusercontent.com/assets/15265570/22181526/5d4f01e2-e0c9-11e6-9267-f7cd9a2637c7.png)

**Comment by QingWei-Li** [comment]
这和 cooking 无关啊

**Comment by 1615450788** [comment]
那eslint是安装在哪的呐? modules里面也没有呀-。-

**Comment by QingWei-Li** [comment]
我的意思是你全局安装了 eslint，那么能不能跑就和 cooking 无关。。。

**Comment by 1615450788** [comment]
其实我就想问问在怎样通过cooking去执行eslint检查某个文件

**Comment by QingWei-Li** [comment]
扩展 cooking 指令咯 http://cookingjs.github.io/zh-cn/list-of-commands.html

https://github.com/cookingjs/cooking-test-command

没精力写 🤷‍♀️

**Comment by 1615450788** [comment]
好吧，顺便问问cooking是整合了eslint的吗？eslint的安装位置在哪？

**Comment by QingWei-Li** [comment]
eslint 是作为 cooking 的插件（cooking-lint）安装在 `~/.cooking`（用户根目录）

**Comment by 1615450788** [comment]
好的，找到了，谢谢:smile:
