### ISSUE TITLE
关于assetsPath路径问题 

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/cooking#149]
目前我的需求`publicPath` 设置了相对路径 `./`
`assetsPath`也设置了相对路径`../images`

```JavaScript
  publicPath: './',
  assetsPath: '../images',

```
但这样打包后image就不在dist目录了 这个有办法吗 - -

**Comment by QingWei-Li** [comment]
publicPath 只能是绝对路径

**Comment by yelingfeng** [comment]
我们需求比较特殊 如果不支持 那就只能这样了

**Comment by QingWei-Li** [comment]
无论什么需求 publicPath 也只能是绝对路径。但是 publicPath 可以是动态设置
