### ISSUE TITLE
有karma搭建的工程例子吗

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/cooking#153]
cooking 怎么配置karma.config.js

**Comment by QingWei-Li** [comment]
https://github.com/cookingjs/slush-cooking-vue

用自带的脚手架可以选择生成单元测试部分的，但是之前有 bug，升级一下脚手架就好了

**Comment by yelingfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1932350/23294155/002c79f4-faa5-11e6-9370-7fc0c2282dda.png)
启动报错

**Comment by QingWei-Li** [comment]
cooking-karma 也要升级，里面的 karma-webpack 要最新的

**Comment by yelingfeng** [comment]
cooking里的karma始终0.13 也不更新啊 我去根目录手动更新得

**Comment by QingWei-Li** [comment]
目前版本是 0.2.0，那你 `cooking remove karma` 再 `cooking import karma` 吧

**Comment by yelingfeng** [comment]
![image](https://cloud.githubusercontent.com/assets/1932350/23297362/35cb4950-fab4-11e6-917c-b97c15fe2d1d.png)
`babel-polyfill` `es6-shim`都不好使 崩溃了

**Comment by QingWei-Li** [comment]
那我抽空改下配置吧，这配置还是 webpack 1 的 一直没空改

**Comment by yelingfeng** [comment]
大神什么时候会更新
