### ISSUE TITLE
请问cooking如何配置vux

### ISSUE THREAD

**Issue by lileltp** [ElemeFE/cooking#159]
如题
`const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(webpackConfig, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    }
    ]
})`

这个用cooking怎么写?

`cooking.add('loader.vux', {
  test: /\.vue$/,
  loaders: ['vux-loader'],
  plugins: [
    {
      name: 'vux-ui'
    }
  ]
})`
我这么写在移动设备上有问题.

**Comment by lileltp** [comment]
`const config = cooking.resolve()
const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(config, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    }
  ]
})`
写成这样直接vue-loader也不起作用了

**Comment by jazzthinking** [comment]
cooking.conf.js 最后这样写

const vuxLoader = require('vux-loader')
module.exports = vuxLoader.merge(cooking, {
  options: {},
  plugins: [
    {
      name: 'vux-ui'
    }
    ]
})

module.exports = cooking.resolve();

**Comment by lileltp** [comment]
@jazzthinking 
使用上面的在开发中可以正常使用了.
但是在dist的时候
ERROR in js/vendor.1e7e760.js from UglifyJs
Unexpected character '`' [./~/vux/src/libs/router.js:14,0][js/vendor.1e7e760.js:1346,11]
又有了这样的问题.

**Comment by jazzthinking** [comment]
@lileltp 我也出这个错误，好像不识别新模板语法里的'`'，但dist后的文件还是可以发布出去访问的，貌似没有问题

**Comment by gengxuelei** [comment]
有人知道怎么配置吗，这个问题不知道是vux的问题还是cooking的问题，我感觉是自己的问题
https://github.com/airyland/vux/issues/1491#issuecomment-305452832

**Comment by lileltp** [comment]
@gengxuelei 建议还是使用webpack吧.我现在用webpack实现了cooking要配置的东西.如果用cooking就只用和他配合的框架好了.否则确实太麻了.
