### ISSUE TITLE
npm link cooking

### ISSUE THREAD

**Issue by furybean** [ElemeFE/cooking#16]
这个可能并不靠谱，用户安装的 cooking 有可能是通过 cnpm 安装的，这样就 link 到了一个空的目录。

可能通过 which cooking，然后再执行 ln -s path 比较靠谱。

**Comment by QingWei-Li** [comment]
测试了一下用 cnpm 全局安装的模块，执行 npm link <name> 后，可以用 require('name') 的。

而且用 ln -s path 貌似 window 不能用？

**Comment by QingWei-Li** [comment]
看来可以不用 link 了，通过增加 NODE_PATH 的方式就能让 require 找到全局的 package 了 😂

**Comment by furybean** [comment]
👍
