### ISSUE TITLE
如何用不同的conf文件来启动cooking watch呢？

### ISSUE THREAD

**Issue by csonezp** [ElemeFE/cooking#160]
例如，在不同的情况下分别启动cooking.conf.prod.js或cooking.conf.dev.js?

**Comment by QingWei-Li** [comment]
```bash
cooking -c cooking.conf.prod.js
cooking -c cooking.conf.dev.js
```

**Comment by yipcma** [comment]
I'm curious how to set env for cooking in a way similar to the defineplugin. Thanks a lot for your help in advance.
