### ISSUE TITLE
cooking配置打包clean为true时，有没有办法配置exclude掉dist中某些文件夹呢？

### ISSUE THREAD

**Issue by matuobasyouca** [ElemeFE/cooking#162]
前后端分离开发，打包到共同目录下，有些后端文件不能删掉。是否有办法指定不删除某些文件夹呢？
多谢了。

**Comment by QingWei-Li** [comment]
打包后再把文件拷进去

**Comment by matuobasyouca** [comment]
感谢回复。
new CleanWebpackPlugin(['dist', 'build'], {
            root: ROOT_PATH,
            verbose: true,
            dry: false,
            exclude: ["dist/1.chunk.js"]
        }),
webpack的插件是可以设置的，cooking内置是没有这个配置的，是么？

**Comment by QingWei-Li** [comment]
没有用这个插件，我直接 `rm` 的，可以配置 [static](http://cookingjs.github.io/zh-cn/configuration.html#static-10) 或者自己写脚本拷贝进去

**Comment by matuobasyouca** [comment]
好的，那我也用命令操作了。
