### ISSUE TITLE
Generator函数如何配置？

### ISSUE THREAD

**Issue by piixiu** [ElemeFE/cooking#167]
cooking version 1.5.0

在代码中使用到Generators

npm run dev

ERROR in ../Users/lvxianfu/.cooking/~/buble-loader?objectAssign=Object.assign&jsx=h!./~/vue-loader/lib/selector.js?type=script&index=0!./example/app.vue
Module build failed: 
24 :       this.$refs.upload.clear();
25 :     }
26 :   },
27 :   created() {
28 :     function* gen() {
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Generators are not supported (28:4)

**Comment by QingWei-Li** [comment]
查看 babel 文档
