### ISSUE TITLE
 怎么设置cooking编译出的js名称

### ISSUE THREAD

**Issue by a1029563229** [ElemeFE/cooking#177]
### cooking version

1.5
### What is Expected?
怎么设置cooking编译出的js名称
### What is actually happening?
找了文档很久，都没找到，现在都是1234567，我有这个需求是因为需要迭代更新，只替换变更文件，或者有更好的迭代更新方法吗？

**Comment by QingWei-Li** [comment]
```js
cooking.add('output.filename', 'xxx')
``

具体看 webpack 文档

**Comment by a1029563229** [comment]
我花了两小时换了个脚手架 然后你回复了...
@QingWei-Li 
qwq
