### ISSUE TITLE
待开发插件列表

### ISSUE THREAD

**Issue by QingWei-Li** [ElemeFE/cooking#18]
- [x] cooking-postcss 提供 postcss-loader 及其基本插件
- [ ] cooking-jade(pug) 
- [x] cooking-salad

...

**Comment by furybean** [comment]
感觉 cooking-jade 优先级不高。
postcss 这个可以优先级高，优先集成 salad 。

**Comment by QingWei-Li** [comment]
cooking-saladcss 已集成 然后现在 import 功能没法监听文件变化 🌚

用法，参考 example/landingpage 
```javascript
{
  extends: ['saladcss']
}
```
