### ISSUE TITLE
cooking init vue无反应

### ISSUE THREAD

**Issue by Cacivy** [ElemeFE/cooking#30]
执行cooking init vue
[cooking] - 下载脚手架相关依赖
[cooking] - downloading 'slush-cooking-vue'
[cooking] - 脚手架安装成功

[cooking] - generator project
然后文件夹下没有任何反应

手动安装 npm install slush-cooking-vue报错

npm ERR! tar.unpack untar error C:\Users\Cacivy\AppData\Roaming\npm-cache\slush-cooking-vue\0.1.8\package.tgz****

**Comment by QingWei-Li** [comment]
Hi, 抱歉没有在 window 上测试过。你检查下 NPM 版本是不是 3.0 以上，然后这里有解决方案你试试看 
https://github.com/npm/npm/issues/10455

**Comment by debenzhang** [comment]
遇到同样问题了

windows 10 64bit 
nodejs v4.4.4 
npm v3.9.0

**Comment by QingWei-Li** [comment]
@debenzhang @Cacivy Hi,
请问你们可以在 win 上用 cooking watch 启动项目么，不使用脚手架。 这里有一个 cooking 的项目 [example/landingpage](https://github.com/ElemeFE/cooking/tree/master/example/landingpage)，或者或者这个  [vue-toast-mobile](https://github.com/ElemeFE/vue-toast-mobile)，我好排除一下是哪些问题。

**Comment by debenzhang** [comment]
@QingWei-Li  正在试着学习前端，clone 了一份在本地跑 cooking watch 得到的结果，不知是否有帮助。

`C:\Users\xxxxx\Desktop\cooking-master\example\landingpage>cooking watch
[cooking] - 依赖包不存在，自动下载依赖包: vue
[cooking] - 插件不存在，自动下载插件: vue
[cooking] - Failed to read the config.
[cooking] - Error: Cannot find module 'cooking-vue'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at importExtend (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\.cooking_npminstall\cooking\0.4.3\cooking\util\load-extend.js:7:3)
    at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\.cooking_npminstall\cooking\0.4.3\cooking\util\load-extend.js:35:5
    at Array.forEach (native)
    at module.exports (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\.cooking_npminstall\cooking\0.4.3\cooking\util\load-extend.js:26:31)
    at Object.exports.set (C:\Users\xxxxx\AppData\Roaming\npm\node_modules\.cooking_npminstall\cooking\0.4.3\cooking\lib\cooking.js:26:3)
    at Object.<anonymous> (C:\Users\xxxxx\Desktop\cooking-master\example\landingpage\cooking.conf.js:3:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)`

**Comment by QingWei-Li** [comment]
@debenzhang @Cacivy Hi, all
windows 无法使用的 bug 已修复，更新至 0.4.4

**Comment by Cacivy** [comment]
ok，npm update还是失败，重装解决

**Comment by debenzhang** [comment]
@QingWei-Li Tks.

**Comment by debenzhang** [comment]
@QingWei-Li 请问，每次 cooking watch 或者 cooking build 之后，都会提示：

$ cooking build
[cooking] - 插件不存在，自动下载插件: vue
[cooking] - 安装插件: vue
[cooking] - 安装成功
[cooking] - 插件加载成功: vue
[cooking] - 插件不存在，自动下载插件: lint
[cooking] - 安装插件: lint
[cooking] - 安装成功
[cooking] - 插件加载成功: lint

请问，这种情况应该怎么处理呢？

**Comment by QingWei-Li** [comment]
@debenzhang , Hi

我刚才在 Win 8.1 虚拟机上测试并重装测试，未出现类似情况。我看到你之前提供的日志似乎是用 cnpm 进行安装的，之后如果又重装的话由于缓存原因可能会导致路径查找混乱。所以解决方法是

1. 卸载全局的 cooking
2. 清理 cnpm 安装过的缓存 `node_modules\.cooking_npminstall`
3. 用 `npm install cooking -g --registry=https://registry.npm.taobao.org` 安装

参考 #35

**Comment by debenzhang** [comment]
@QingWei-Li 的确是用 cnpm 跑的，我现在按照你给的步骤再试一下。
Thanks for your reply.

**Comment by debenzhang** [comment]
@QingWei-Li 问题找到啦，主要的原因并不是 cnpm 造成的，而是系统的 Python 版本是 3，这时候，有一个依赖包跑不起来，而我又是 newer，没有发现。系统 Python 版本换成 2 之后，目前一切顺利。Thank you for your support.

**Comment by QingWei-Li** [comment]
@debenzhang 还有这问题？哪个插件？我更新下文档...

**Comment by debenzhang** [comment]
@QingWei-Li 我不是很懂 nodejs 的包，看起来貌似是 gyp。

gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.

**Comment by QingWei-Li** [comment]
@debenzhang THX， 查了下文档官方只支持 2.7+ https://www.npmjs.com/package/node-gyp

**Comment by debenzhang** [comment]
@QingWei-Li My bad. 一直在 cooking 这里找问题，方向错了。
