### ISSUE TITLE
运行cooking create firstvue vue后只创建了目录，目录下没有生成任何文件

### ISSUE THREAD

**Issue by Jinkeycode** [ElemeFE/cooking#34]
MacOS 10.11.4

{ npm: '3.8.6',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '48',
  node: '6.1.0',
  openssl: '1.0.2h',
  uv: '1.9.0',
  v8: '5.0.71.35',
  zlib: '1.2.8' }

运行cooking create firstvue vue后只创建了目录，目录下没有生成任何文件。

**Comment by QingWei-Li** [comment]
有无报错？麻烦发下输出结果。创建后并不会自动进入 firstvue 目录，需要自己进入

**Comment by Jinkeycode** [comment]
![image](https://cloud.githubusercontent.com/assets/12148377/15346423/abfac5a4-1cea-11e6-9ea2-08d693fd7b36.png)
没有任何的错误提示，我有手动进入firstvue目录（不在截图区域内）下一个文件都没有

**Comment by QingWei-Li** [comment]
我换了 node 6.1 测试了下并未出现这个情况。我怀疑还是权限问题，不然不可能创建不了文件

你可以试试把权限改成当前用户
```shell
sudo chmod -R 用户名 /usr/local/lib/node_modules/
```

**Comment by Jinkeycode** [comment]
同步一下别人教的解决办法：

先执行
`npm install -g cooking --force`
完成后再次执行
`cooking create firstvue vue`

**Comment by Jinkeycode** [comment]
同步一下别人教的解决办法：

先执行
`npm install -g cooking --force`
完成后再次执行
`cooking create firstvue vue`
