### ISSUE TITLE
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/.cooking_npminstall/cooking/0.4.4/cooking/.cooking'

### ISSUE THREAD

**Issue by baijunyao** [ElemeFE/cooking#38]
按照文档创建项目报错；提示没有权限；无法使用sudo；请问需要怎么解决？谢谢；
<img width="574" alt="error" src="https://cloud.githubusercontent.com/assets/9360694/15449261/314fce12-1fab-11e6-94ad-bd8fbffc06ac.png">

**Comment by QingWei-Li** [comment]
你好，请参考文档的 [常见问题:Cannot find module 'xxx'](https://github.com/ElemeFE/cooking#cannot-find-module-xxx)

#37 #35 #29

**Comment by baijunyao** [comment]
按照您的方案；已经解决；非常感谢；
