### ISSUE TITLE
This is an issue with the `slush-cooking-vue` generator  报错是怎么回事？

### ISSUE THREAD

**Issue by chengwangping** [ElemeFE/cooking#43]

**Comment by QingWei-Li** [comment]
麻烦把发下错误日志

**Comment by chengwangping** [comment]
[cooking] - generator project
[09:40:20] No local gulp install found in /Users/admin/.cooking/node_modules/slush-cooking-vue
[slush] This is an issue with the `slush-cooking-vue` generator

**Comment by QingWei-Li** [comment]
请使用 NPM3 安装 cookingSent from iPhone
            在2016年06月01日 09:45，cwp 写道:[cooking] - generator project
[09:40:20] No local gulp install found in /Users/admin/.cooking/node_modules/slush-cooking-vue
[slush] This is an issue with the slush-cooking-vue generator

**Comment by chengwangping** [comment]
node版本是b 6.2.0 
npm 版本是 3.8.9
版本应该没问题的

**Comment by QingWei-Li** [comment]
我测试过用 node 6+ 和 npm 3+ 安装后并无问题，那你试试把 ` /Users/admin/.cooking` 删掉重新运行 cooking

**Comment by QingWei-Li** [comment]
@chengwangping Hi
请问下问题解决了么
