### ISSUE TITLE
多入口资源加载问题

### ISSUE THREAD

**Issue by minerchow** [ElemeFE/cooking#50]
我有两个入口，src/index.tpl和src/pages/activity/activity.tpl,为什么index.tpl入口会加载activity.js，activity.tpl会加载app.js(index.tpl下js文件)
![a](https://cloud.githubusercontent.com/assets/3675138/15965225/273cc1ce-2f4f-11e6-8d91-15d15c2cf6d6.png)
![b](https://cloud.githubusercontent.com/assets/3675138/15965237/35997820-2f4f-11e6-83dd-4138fdbf7642.png)
![c](https://cloud.githubusercontent.com/assets/3675138/15965242/3e46590c-2f4f-11e6-92b6-54d5e049f24a.png)

![d](https://cloud.githubusercontent.com/assets/3675138/15965585/56a7234e-2f51-11e6-9304-a71527c2ba49.png)

**Comment by QingWei-Li** [comment]
有几个问题

1. chunk 传入的对象，三个键值对的键名都是一样的。这肯定不行，只有最后一个才生效。所以你的 commonChunk 的配置并没有生效。
2. template 本质上是把你传入的对象转成数组后传入 `html-webpack-plugin`，而这个插件接受的参数[见这里](https://github.com/ampedandwired/html-webpack-plugin)，你把 `chunks` 写成了 `chunk` 所以并没有生效，导致所有的入口都引入到了模板里。

**Comment by minerchow** [comment]
刚刚版本升到0.4.9之后就报错了

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.5.3
3 info using node@v4.4.5
4 verbose stack Error: Invalid version: "*"
4 verbose stack     at Object.module.exports.fixVersionField (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:191:13)
4 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
4 verbose stack     at final (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:338:5)
4 verbose stack     at then (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:232:12
4 verbose stack     at C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd D:\work\cookingProject
6 error Windows_NT 6.1.7601
7 error argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
8 error node v4.4.5
9 error npm  v3.5.3
10 error Invalid version: "*"
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by minerchow** [comment]
谢谢解答，参考你给我配置，common.js和app.js都被载入了vue.js，这并不是我想要的
![image](https://cloud.githubusercontent.com/assets/3675138/15970382/e37b3bc4-2f66-11e6-94e8-ef4c8d6418ee.png)


var path = require('path');
var cooking = require('cooking');

cooking.set({
  entry: {
    app: './src/main.js',
    activity:'./src/pages/activity/main.js',
    vendor: ['vue'],
    common:['./src/common/common.js'],
    commonCss:['./src/common/common.css']
  },
  dist: './dist',
  template: [{
     filename:"index.html",
      template:'./src/index.tpl',
      chunks:['vendor','common','app']
    },
    {
      filename:"activity.html",
      template:'./src/pages/activity/activity.tpl',
      chunks:['vendor','common','activity']
    }

  ],

  devServer: {
    port: 8080,
    publicPath: '/'
  },

  // production
  clean: true,
  hash: true,
  sourceMap: true,
  chunk:[
    {
      'name':'vendor',
      'chunks':['vendor']
    },
    {
      'name':'common',
      'chunks':['common']
    }

  ],
  publicPath: '/dist/',
  assetsPath: 'static',
  urlLoaderLimit: 10000,
  extractCSS: '[name].[contenthash:7].css',
  extends: ['vue',  'sass']
});

cooking.add('resolve.alias', {
  'src': path.join(__dirname, 'src')
});
cooking.add('loader.es6', {
  test: /\.es6$/,
  loaders: ['babel-loader']
})

module.exports = cooking.resolve();

**Comment by QingWei-Li** [comment]
temple 里的 chunks 配置了哪个入口就会引入对于的入口文件 

chunks:['vendor','common','app']

所以你会得到那三个文件

**Comment by minerchow** [comment]
index.tpl 确实包含vendor.js,common.js,app.js，这点是没错的，但是app.js里面将vue库文件也一起打包进去了，怎么配置把它分离出去

**Comment by rguanghui** [comment]
```
cooking.add('externals', {
  vue: 'Vue'
});
```

**Comment by QingWei-Li** [comment]
配置多个 chunks 的范例请参考官方文档 https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks 

如果 app 和 vendor 包含 vue 的话，多 chunk 应该这么配置

```javascript
  entry: {
    app: './src/main.js',
    admin: './src/main2.js',
    vendor: ['vue']
  },
  template: [
    {
      filename: 'index.html',
      template: './src/index.tpl',
      chunks: ['vendor', 'app']
    },
    {
      filename: 'admin.html',
      template: './src/index2.tpl',
      chunks: ['vendor', 'admin']
    }
  ],
  chunk: [
    {
      name: 'vendor',
      chunks: ['vendor', 'app']
    }
  ]
```

这样，名为 vendor 的 chunk 会将入口为 vendor 和 app 里公共的部分（也就是 vendor 声明的 vue）给提取出来，如果入口 admin 也包含了 vue 同时也想提取，那么应该配置成
```javascript
{
  chunk: [
    {
      name: 'vendor',
      chunks: ['vendor', 'app', 'admin']
    }
  ]
}
```

**Comment by minerchow** [comment]
,谢谢 QingWei-Li 解答，之前对chunk的理解是错的，现在已经能将文件都分离出来了。
还有个小细节问题，template里面的chunks是不是都会在文件名后面打上.js，现在我有个公用的css文件common.css
![image](https://cloud.githubusercontent.com/assets/3675138/15982625/cc7f1960-2fbe-11e6-8e61-5636c3a1da9a.png)

run dist打包之后common.css的确被单独提取出来了，但同同时会引入一个commomCss.js文件，请问下要怎么处理
![aa](https://cloud.githubusercontent.com/assets/3675138/15982657/b7ca3e54-2fbf-11e6-95ad-67a1a360d8c0.png)

**Comment by QingWei-Li** [comment]
确实会如此，因为 webpack 的 entry 传的值应该是 js 文件路径，所以传入的文件其实是当做 js 文件处理了。只是 ExtractTextPlugin 把 `commonCss.js` 里的 CSS 部分提取出来，所以现在 `commonCss.js` 只有 webpack 的一些内容，没有实际内容。
不过如果换做我的话，我会在入口 `common` 里引入 `common.css` 文件，也就是
```javascript
common: ['./src/common.js', './src/common.css']
```

**Comment by bibiuc** [comment]
- -还真是个聊天的好地方，我邮箱都嘣嘣嘣的。
