### ISSUE TITLE
搭建react的时候报错

### ISSUE THREAD

**Issue by zhy6421867** [ElemeFE/cooking#53]
C:\Users\user\Desktop\react-cooking>cooking watch

[cooking] - 插件加载成功: react
[cooking] - 插件加载成功: lint
[cooking] - 插件加载成功: postcss

[cooking] - server 启动中...
[cooking] - Listening at http://localhost:8080
Child cooking.conf.js:

    ERROR in ./src/app.js
    Module build failed: ReferenceError: [BABEL] C:\Users\user\Desktop\react-coo
king\src\app.js: Unknown option: C:\Users\user\Desktop\react-cooking\node_module
s\react\react.js.Children. Check out http://babeljs.io/docs/usage/options/ for m
ore info

估计是编译的问题

**Comment by QingWei-Li** [comment]
@zhy6421867, Hi

**Comment by zhy6421867** [comment]
没改动过什么,创建react的指令都运行了,运行cooking watch的时候就会报这个错.

vue项目可以跑起来,不过创建的时候提示缺少好几个npm第三方模块,都是一个个手动安装上去,vue才能跑起来.用的是npm3,而且已经翻墙了.明天到公司再试试,问题出在哪里.

最后,你们的cooking很棒,感谢!

**Comment by QingWei-Li** [comment]
不可能啊 却少什么模块？你把完整日志发一下。还有你的 Node 和 NPM 版本。win8.1 上我测过的可以用。确保 Node 4+ 和 NPM3+；还有问题的话，把用户目录下的 .cooking 删除掉再试试；最后确保是用 NPM 安装的 cooking 而不是 cnpm 或 pnpm 之类的，没测试过不保证能用。

**Comment by zhy6421867** [comment]
问题解决了.

我以前安装的是长期支持版的Node.刚刚换成最新稳定版的,按照流程走一遍,可以搭建react开发环境了.

再次感谢!
