### ISSUE TITLE
url-loader转出的base64图片裂了

### ISSUE THREAD

**Issue by minerchow** [ElemeFE/cooking#54]
如图，图片的确转成base64了，但为什么转挂了...
![image](https://cloud.githubusercontent.com/assets/3675138/15992103/9b5d7b76-30f7-11e6-8ea0-4e824d57ba21.png)
![image](https://cloud.githubusercontent.com/assets/3675138/15992105/b0d3ca14-30f7-11e6-937b-012de329da24.png)
![image](https://cloud.githubusercontent.com/assets/3675138/15992119/f26d0ec2-30f7-11e6-9fec-a87003ea4625.png)
![image](https://cloud.githubusercontent.com/assets/3675138/15992124/10e30dfc-30f8-11e6-820c-288c8344bef8.png)

**Comment by QingWei-Li** [comment]
因为源码里已经有了 loader.image，而你的配了 loader.url 并没有覆盖掉 loader.image 的配置，导致 png 文件被 `url-loader` 处理了两次，导致挂掉。
```javascript
        image: {
          test: /\.(gif|png|jpe?g)(\?\S*)?$/,
          loader: 'url-loader',
          query: {
            limit: limit,
            name: path.join(assetsPath, '[name].[hash:7].[ext]')
          }
```

下次提问可以到 gitter 里（首页文档有链接）🌚
