### ISSUE TITLE
请问初始化的时候报错 要怎么解决？

### ISSUE THREAD

**Issue by hee93** [ElemeFE/cooking#56]
No local gulp install found in /Users/hao/.cooking/node_modules/slush-cooking-vue
[slush] This is an issue with the `slush-cooking-vue` generator

**Comment by QingWei-Li** [comment]
需要 NPM 3 以上版本才能运行。
升级 NPM 后，移除 `~/.cooking` 目录，并重新安装 `cooking`

**Comment by hee93** [comment]
好的 谢谢 我谢谢

**Comment by hee93** [comment]
好的 我试试
