### ISSUE TITLE
This is an issue with the `slush-cooking-vue` generator

### ISSUE THREAD

**Issue by WriterLuo** [ElemeFE/cooking#61]
cooking create my-project vue

..............

[cooking] - generator project
[18:00:21] No local gulp install found in /Users/Writer/.cooking/node_modules/slush-cooking-vue
[slush] This is an issue with the `slush-cooking-vue` generator

========================

npm install slush-cooking-vue -g 

问题依旧

**Comment by QingWei-Li** [comment]
老问题了，要使用 NPM 3+
升级 NPM 后，移除用户更目录下的 `.cooking` 文件，然后重新安装 cooking

**Comment by WriterLuo** [comment]
……回的够快啊
