### ISSUE TITLE
Atom的ESlint报错

### ISSUE THREAD

**Issue by azad112358** [ElemeFE/cooking#62]
Atom编辑器，初始化一个vue项目，然后打开项目中的js文件，提示`Error: Failed to load plugin vue: Cannot find module 'eslint-plugin-vue'`

**Comment by QingWei-Li** [comment]
本地安装一个 `eslint-plugin-vue`

Atom 读不到 `~/.cooking` 路径下的依赖。编辑器默认只能去本地或者全局去读依赖文件

**Comment by azad112358** [comment]
安装了之后，并没有起作用，先是本地安装不起作用，然后全局安装还是不起作用，错误一直提示。

**Comment by QingWei-Li** [comment]
@azad112358 https://github.com/AtomLinter/linter-eslint#use-with-plugins

eslint 有一个限制，eslint 必须和它的插件在同一个目录下 （或者具体指明插件的路径），有点蛋疼
