### ISSUE TITLE
如何进行单元测试？

### ISSUE THREAD

**Issue by SidKwok** [ElemeFE/cooking#63]
没找到test的选项，是尚未支持测试吗？

**Comment by QingWei-Li** [comment]
业务项目很少写测试，至少目前为止没有需求要测试功能，因此一直没做。
cooking 其实有一个隐藏功能是支持扩展指令的，因此完全可以去写一个测试功能的插件，只是没需求 🌚

**Comment by SidKwok** [comment]
Soga
