### ISSUE TITLE
支持将 cooking 安装在项目里

### ISSUE THREAD

**Issue by QingWei-Li** [ElemeFE/cooking#66]
目前 cooking 只能全局安装，但是随着版本迭代，也出现了需要使用不同版本依赖的问题。因此从下一版开始将支持安装 cooking 在本地项目。

## 支持版本 0.7.0 和 1.0.0

计划是 1.0.0 只提供 webpack 2，0.7.x 只提供 webpack 1。同时如果安装在项目里的话，自动安装的 cooking 依赖将会保存在 `package.json` 中。**并不能使用全局的 cooking 依赖**。同时也可以自己管理依赖的其他版本。

**Comment by furybean** [comment]
建议 cooking 0.7 和 cooking 1 能一块使用，.cooking 使用两个不同的文件夹。

**Comment by QingWei-Li** [comment]
@furybean 我是使用 nvm 切换环境，来安装不同版本的 cooking。如果全局安装的话似乎没办法让两个版本共存，除非换不同的命令名？比如 cooking 和 cooking-next ?

**Comment by QingWei-Li** [comment]
换了其他思路，新特性直接放到 1.0 里，同时兼容 webpack 1 和 2 同时解决依赖管理问题同时保留原来全局安装依赖的特性
