### ISSUE TITLE
cooking@0.6.2 windows下init项目报错

### ISSUE THREAD

**Issue by minerchow** [ElemeFE/cooking#68]
![image](https://cloud.githubusercontent.com/assets/3675138/17896143/10e591ea-6982-11e6-873c-f4ea06ff4003.png)
.cooking文件夹已经删除过并且重新安装cooking，之前做的demo用npm run dev是能够跑起来的

**Comment by QingWei-Li** [comment]
@minerchow 找到问题了？

**Comment by minerchow** [comment]
还没，暂时也找不到方案

**Comment by QingWei-Li** [comment]
抱歉

**Comment by minerchow** [comment]
没事，讲不定过几天找到办法解决，貌似是系统某个权限问题，刚刚换了台电脑没有这个问题

**Comment by bugaboo622** [comment]
@minerchow 遇到同样的问题，当时cooking版本为1.5.3版本，降回1.5.2版本后解决了
