### ISSUE TITLE
cooking watch error

### ISSUE THREAD

**Issue by pysjp** [ElemeFE/cooking#82]
E:\work\env\html5\cooking-cli>cooking watch

[cooking] - 插件加载成功: autoprefixer
[cooking] - 插件加载成功: less
[cooking] - 插件加载成功: lint
[cooking] - 插件加载成功: vue

[cooking] - server 启动中...
[cooking] - Listening at http://localhost:8080
'"[object Object]"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by pysjp** [comment]
E:\work\env\html5\cooking-cli>cooking watch

[cooking] - 插件加载成功: saladcss
[cooking] - 插件加载成功: lint
[cooking] - 插件加载成功: vue

[cooking] - server 启动中...
[cooking] - Listening at http://localhost:8080
'"[object Object]"' is not recognized as an internal or external command,
operable program or batch file.
升级为最新的版本，还是报上面的错误，配置信息如下：
E:\work\env\html5\cooking-cli>npm view cooking-cli

{ name: 'cooking-cli',
  time:
   { modified: '2016-09-18T14:11:15.696Z',
     created: '2016-09-05T16:34:04.059Z',
     '1.0.0-rc.1': '2016-09-05T16:34:04.059Z',
     '1.0.0-rc.2': '2016-09-05T17:03:12.388Z',
     '1.0.0-rc.3': '2016-09-06T09:02:45.948Z',
     '1.0.0': '2016-09-11T07:53:50.019Z',
     '1.0.1': '2016-09-11T08:41:16.827Z',
     '1.0.2': '2016-09-12T04:33:32.100Z',
     '1.0.3': '2016-09-12T06:28:29.682Z',
     '1.0.4': '2016-09-12T13:29:27.659Z',
     '1.0.5': '2016-09-14T01:06:09.349Z',
     '1.0.6': '2016-09-14T01:35:20.180Z',
     '1.0.7': '2016-09-14T10:06:07.951Z',
     '1.0.8': '2016-09-14T17:53:11.393Z',
     '1.0.9': '2016-09-15T05:48:39.240Z',
     '1.0.10': '2016-09-16T07:23:23.795Z',
     '1.0.11': '2016-09-18T03:47:50.118Z',
     '1.1.0': '2016-09-18T14:11:15.696Z' },
  maintainers: [ 'qingwei.li <cinwell.li@gmail.com>' ],
  'dist-tags': { next: '1.0.0-rc.2', latest: '1.1.0' },
  versions:
   [ '1.0.0-rc.2',
     '1.0.0-rc.3',
     '1.0.0',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '1.0.4',
     '1.0.5',
     '1.0.6',
     '1.0.7',
     '1.0.8',
     '1.0.9',
     '1.0.10',
     '1.0.11',
     '1.1.0' ],
  description: 'cooking cli.',
  homepage: 'https://github.com/ElemeFE/cooking#readme',
  keywords: [ 'vue', 'webpack', 'build', 'tool', 'react' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/ElemeFE/cooking.git' },
  author: 'qingwei-li <qingwei.li@ele.me>',
  bugs: { url: 'https://github.com/ElemeFE/cooking/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.1.0',
  preferGlobal: true,
  bin: { cooking: 'bin/cooking' },
  engines: { node: '>=4.0.0', npm: '>=3.0.0' },
  dependencies:
   { 'babel-core': '^6.0.0',
     'babel-loader': '^6.0.0',
     'babel-plugin-transform-runtime': '^6.0.0',
     'babel-preset-es2015': '^6.0.0',
     'babel-preset-stage-0': '^6.0.0',
     'babel-preset-stage-2': '^6.0.0',
     chalk: '^1.1.3',
     commander: '^2.9.0',
     cooking: '^1.1.0',
     'cross-spawn': '^4.0.0',
     'css-loader': '^0.24.0',
     'extract-text-webpack-plugin': '^2.0.0-beta',
     'file-loader': '^0.9.0',
     'format-json': '^1.0.3',
     'html-loader': '^0.4.3',
     'html-webpack-plugin': '^2.9.0',
     'json-loader': '^0.5.4',
     postcss: '^5.1.0',
     'postcss-loader': '^0.11.1',
     'progress-bar-webpack-plugin': '^1.6.0',
     shelljs: '^0.7.0',
     slush: '^1.1.1',
     'style-loader': '^0.13.1',
     'update-notifier': '^1.0.2',
     'url-loader': '^0.5.7',
     webpack: '^2.1.0-beta',
     'webpack-dev-server': '^2.1.0-beta',
     'webpack-hud': '*' },
  scripts: {},
  dist:
   { shasum: 'e85127e5e472aa51704f933f4496fac92d6ca3c1',
     tarball: 'https://registry.npmjs.org/cooking-cli/-/cooking-cli-1.1.0.tgz' },
  directories: {} }

工程是使用新版本重新初始化的

**Comment by QingWei-Li** [comment]
执行下 `-V` 看看版本号
```shell
cooking -V
```

**Comment by pysjp** [comment]
E:\work\env\html5\cooking-cli>cooking -V

1.0.3

这里看到还是旧的版本号，但是我已经执行了npm update cooking-cli，上面的view也可以看到到最新了

**Comment by QingWei-Li** [comment]
不不，你通过 npm view 看到的是 npm 线上的信息，并不是你安装的包的信息。

注意加 `-g` ，全局安装
```shell
npm i cooking-cli -g
```
