### ISSUE TITLE
加载less模块失败

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/cooking#86]
系统: win7
Node: 5.12
Npm: 3.8.6
cooking: 1.0.7

一切按提示安装, css处理那里选择了 less, watch的时候报错
![image](https://cloud.githubusercontent.com/assets/10840991/18513388/db89f2da-7abf-11e6-8691-b302558859d3.png)

\.cooking\node_modules\cooking-less\less-loader.js

```
  // if (nextVersion) {
  //   nextVersion = Number(nextVersion.split('.')[0])
  // }
```
没看明白这三行代码的作用, 注释后运行成功...

**Comment by QingWei-Li** [comment]
...忘记去掉了

**Comment by QingWei-Li** [comment]
fixed in https://github.com/webjyh/cooking-less/commit/6f075f62d1c3f2dc23251f99431514dbb204c24d

执行 update 升级插件
```shell
cooking update less
```
