### ISSUE TITLE
如何配置 devtool, 支持 Chrome 的断点功能

### ISSUE THREAD

**Issue by GuoYiJi** [ElemeFE/cooking#87]
您好，我想问下，cooking如果配置才能打断点呢，现在打不了断点

**Comment by QingWei-Li** [comment]
支持的，默认配置的 devtool 是 eval-source-map

你可以改成你需要的，直接给 cooking.config.devtool 赋值，或者用 cooking.add('devtool', xxx)

有哪些可选值自行参考 webpack 的 devtool 文档

**Comment by GuoYiJi** [comment]
好的，蟹蟹。

**Comment by QingWei-Li** [comment]
默认配置下，启动 webpack 后可以在 chrome 的开发者工具的 sources 看到 `webpack://`，里面就是你的「源码」
![cooking](https://cloud.githubusercontent.com/assets/7565692/18623456/e6a50cdc-7e6f-11e6-8179-c5186ba7b1a1.gif)
