### ISSUE TITLE
如果添加后端服务器该如何配置？

### ISSUE THREAD

**Issue by shortbaby** [ElemeFE/cooking#88]

**Comment by QingWei-Li** [comment]
如果是后端提供 API 服务，需要设置代理。参考 webpack-dev-server 的配置
https://github.com/webpack/webpack-dev-server/blob/master/examples/proxy-advanced/webpack.config.js#L4-L19

**Comment by shortbaby** [comment]
也就是说 这个配置和cooking的config关系不大 ，只需要设置devServer的参数配置咯？

**Comment by QingWei-Li** [comment]
是的，直接配置在 devServer 里，因为最终生成的就是 webpack 配置
