### ISSUE TITLE
cooking build failed

### ISSUE THREAD

**Issue by Plortinus** [ElemeFE/cooking#93]
`npm i cooking-cli -g`是这样安装的，安装后`cooking watch`没问题，`cooking build`失败
### cooking version
1.1.1

### What is actually happening?

> cooking build
> 
> [cooking] - Loaded success: autoprefixer
> [cooking] - Failed to read the config.
> [cooking] - Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
> Example: if your old code looked like this:
>     ExtractTextPlugin.extract('style-loader', 'css-loader')
> 
> You would change it to:
>     ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader' })
> 
> The available options are:
>     loader: string | object | loader[]
>     fallbackLoader: string | object | loader[]
>     publicPath: string

**Comment by QingWei-Li** [comment]
vue 插件没升级。如果你用的是 1.0.0 的 cooking 需要执行

```shell
cooking remove vue && cooking import vue
```

如果是 1.1.0 那么就直接 `cooking update vue`

但是现在建议 `cooking-vue` 安装在当前项目内，参考最新的脚手架

**Comment by Plortinus** [comment]
用的`cooking-cli`的版本是1.1.1

我执行的步骤是：

1. `sudo npm i cooking-cli -g`
2. `cooking create my-project vue`
3. `cooking watch`（成功）
4. `cooking build`（失败）
5. `cooking update vue`
6. `cooking build` （失败）

失败提示依旧是上面的写的那个提示语

**Comment by QingWei-Li** [comment]
之前插件没清理掉，所以 update 还是没用的。把用户目录下的 `.cooking` 文件整个删掉吧，还有别用 sudo 了，会有问题的

**Comment by Plortinus** [comment]
删掉`.cooking`文件夹就可以了
