### ISSUE TITLE
当extends了less, 并配置postcss的autoprefixer时, 编译less文件出错

### ISSUE THREAD

**Issue by lincenying** [ElemeFE/cooking#95]
cooking版本: 1.0.11

当extends了less, 并配置postcss的autoprefixer时, 编译less文件出错

把loader打印出来后, 发现顺序是: `style-loader!css-loader!less-loader!postcss-loader`

正常顺序应该是: `style-loader!css-loader!postcss-loader!less-loader`

另外有没有配置css-loader参数的地方?  比如我css-loader要加 `-autoprefixer`参数

现在不得不用这种写法:
```
if (process.env.NODE_ENV === 'production') {
    cooking.add('loader.css', {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract(['css?-autoprefixer', 'postcss'])
    })
    cooking.add('loader.less', {
        test: /\.less/,
        loader: ExtractTextPlugin.extract(['css?-autoprefixer', 'postcss', 'less'])
    })
} else {
    cooking.add('loader.css', {
        test: /\.css$/,
        loader: 'style!css?-autoprefixer!postcss'
    })
    cooking.add('loader.less', {
        test: /\.less/,
        loader: 'style!css?-autoprefixer!postcss!less'
    })
}
```

**Comment by QingWei-Li** [comment]
第一个问题我一会升级下 cooking-less
第二个问题，css-loader 有 autoprefixer 选项么？就算有的话，webpack 2 推荐通过 webpack. LoaderOptionsPlugin 来设置 option，例如 cooking 的 minimize 选项就是通过这个插件添加的 `minimize` 选项

**Comment by QingWei-Li** [comment]
fixed in https://github.com/webjyh/cooking-less/commit/da1be91281bb9ca76b63d743f4384f273f681476

**Comment by lincenying** [comment]
`-autoprefixer` 这个参数是阻止css-loader把一些它认为过期的css3的私有前缀给删了...比如`display: -webkit-flex`

`LoaderOptionsPlugin`在doc里没找到, 在issues里找到了...谢谢...
