### ISSUE TITLE
整合vux组件的vue项目编译失败

### ISSUE THREAD

**Issue by adonishong** [ElemeFE/cooking#96]
首先，感谢您的项目^_^

我们的vue项目使用了vux组件，如果使用webpack进行编译，需要在loaders里面配置这个
      {
        test: /vux.src.*?js$/,
        loader: 'babel'
      },
于是迁移到cooking后，我们配置了这个
cooking.add('loader.vux', {
  test: /vux.src.*?js$/,
  loaders: ['babel']
})
npm run cooking build的时候先是提示安装cooking-babel，于是我们也装了，但是build还是出诸如以下状况的错误
ERROR in 27.40f654d.js from UglifyJs
SyntaxError: Unexpected token: name (Style) [27.40f654d.js:100,8]

我们查看了一下相关的代码，发现出错部分都是“import..."，我们判断这里应该是loader配置方面还是有问题，vux还是没有用babel进行编译

希望得到您的回复，谢谢^_^

**Comment by QingWei-Li** [comment]
1. 应该不会提示安装 cooking-babel 的，你是在 `extends` 里配置了 babel 了？
2. 你的 test 没写对，vux 的文档写的是 `/vux.src.*?js$/`

这是我的配置（省略了其他内容）
```javascript
var cooking = require('cooking');

cooking.set({
  entry: './src/main.js',
  dist: './dist',
  minimize: true,
  extends: ['vue', 'less']
});

cooking.add('loader.vux', {
  test: /vux.src.*?js$/,
  loader: 'babel-loader'
})

module.exports = cooking.resolve();
```

**Comment by adonishong** [comment]
感谢您的回复^_^

用您的配置，我这边build没问题了。

不过发现一个问题，其实我的配置和您的区别不是test那行，那行的问题可能是编辑器在复制过程中出问题，或者是我编辑的时候不小心自己删掉的。实际问题发生在，我的配置里cooking.set(...)在cooking.add(...)后面，您的相反，我把我的配置里cooking.set和cooking.add颠倒后就OK了。

这个在顺序方面的耦合文档里没有看到，希望类似的问题能在文档里有所反映，避免后人踩坑。

无论如何，感谢楼主的项目^_^

**Comment by QingWei-Li** [comment]
ok

**Comment by adonishong** [comment]
遇到新问题，开新的issue么？看起来不同vue文件使用相同的组件，结果这些组件在build出来的js里出现了很多次。如果是webpack那边的配置，应该是机遇commonschunk相关配置解决，不知道cooking这边怎么处理？话说，就是因为commonschunk没玩顺所以尝试考虑cooking的。。。

**Comment by QingWei-Li** [comment]
可以通过 set 里的 [chunk](http://cookingjs.github.io/zh-cn/configuration.html#chunk) 设置。默认配置和 vue 的那套 webpack 模板一样，其他的还是需要自己配置，不过以后会考虑把 chunk 弄得简单些
