### ISSUE TITLE
webpack 2.1.0-beta.25 cooking watch报错

### ISSUE THREAD

**Issue by yelingfeng** [ElemeFE/cooking#99]
![qq 20161009100724](https://cloud.githubusercontent.com/assets/1932350/19217237/48aeaf3a-8e08-11e6-8687-9bef01f8d3a3.png)
![1lu6x5 0 rq e o6e2j 99](https://cloud.githubusercontent.com/assets/1932350/19217254/bb6ca0a4-8e08-11e6-8f8c-6a92d98bbe18.png)

### cooking version

1.1.3

win10/chrome53

node v6.6
npm v3.10.3

**Comment by QingWei-Li** [comment]
现在只兼容 beta 22

**Comment by yelingfeng** [comment]
了解
